### ISSUE TITLE
Amazing package! Two feature ideas…

### ISSUE THREAD

**Issue by inxilpro** [stevebauman/unfinalize#1]
Woo, you made the package!

Two thoughts…

1. Would it make sense to use the `@internal` annotation rather than `@final`? Something like: `@internal class was originally final`. At least in PhpStorm, if you extend a class in a vendor directory that's marked as `@internal` that triggers a weak warning. It might be nice to have that option.

2. Would you consider a PR to optionally elevate `private` to `protected` as well? I think the same would make sense…

Something like this in the end…

```diff
+ /** @internal Was originally `final` */
- final class Example
+ class Example
  {
-   private function foo()
+   /** @internal Was originally `private` */
+   protected function foo()
  }
```

**Comment by deleugpn** [comment]
changing `private` methods into `protected` is the cherry on the cake 😈

**Comment by stevebauman** [comment]
Hey @inxilpro!

1. I actually initially made it internal, but I received a couple comments on that implementation and they requested if it could be `@final` instead: https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.final.pkg.html
2. I would definitely accept a PR for that! Anything that gives us that sweet freedom 👍

**Comment by ilnytskyi** [comment]
@stevebauman is there a way or config to make annotation on same line as final keyword or run it before composer patches?
```
/** @final */
```

It looks like when unfinalize is run before composer patches eg https://github.com/cweagans/composer-patches it will break the installation or upgrade due to line shift in `.patch | .diff` files

**Comment by stevebauman** [comment]
@ilnytskyi We could, but wouldn't that still result in the same issue since a single line is still being inserted? Correct me if I'm wrong.

I would think if you're needing composer patches to work, I'd personally avoid adding annotations, since it'll always be inserting new content and shifting the lines, rather than removing a keyword inside of the same line.

**Comment by ilnytskyi** [comment]
@stevebauman I meant smth like this without inserting the line, but maybe it's just better to avoid adding annotations to make patches work
```
/** @final */ class MyClass {}
```

Regarding the original topic the rule might be based on this class, just substitute tokens, or make them configurable.
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Fixer/ClassNotation/ProtectedToPrivateFixer.php

But in my case I would like sometimes make some private methods protected/public but leave properties as it is.
Mostly because of I just want to decorate a private method in a core/god class that's impossible or hard to override due to its dependencies/size/complexity/bad design/composition.
https://symfony.com/doc/current/service_container/service_decoration.html

**Comment by stevebauman** [comment]
@ilnytskyi Ahh I see. Yea we could probably do that, and enable it with an option value:

```bash
@php vendor/bin/unfinalize run --mark-final=inline
```

> But in my case I would like sometimes make some private methods protected/public but leave properties as it is.

Yea I think we can have both as options here as well, something like:

```
@php vendor/bin/unfinalize run --private=methods,properties
```

Thoughts?

**Comment by therecluse26** [comment]
Ooo! Ooo! A few more feature requests: 

1) Expose all environment variables as response headers for every request
2) Remove the class altogether and expose all class methods as global functions
3) Decrypt all encrypted database fields and store them as plain text
4) Why stop at making `private` methods `protected`? Make them `public`!

🏴

**Comment by stevebauman** [comment]
@therecluse26 I love those ideas! Let's keep it flowing 👍
