### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by misterabdul** [stevebauman/unfinalize#3]
I'm kindly asking because I've never stumbled upon this problem.

First, why does PHP have the `final` keyword and why would anyone make their classes as `final`?

Second, I'd like to know some examples of actual use cases of this package, could you explain in more detail? I'm curious.

**Comment by stevebauman** [comment]
Hi @misterabdul,

The `final` keyword disables inheritance. This package removes the `final` keyword in specific vendor packages so classes that were previously marked final can be extended.

**Comment by mbabker** [comment]
This issue should be re-opened, or converted to a discussion using the appropriate GitHub feature (presuming it was enabled on this repository).

You have managed to skirt around answering both questions posed by the OP with a purely philosophical answer.

An important point in marketing the usability of any tool is providing examples of concrete use cases where the tool solves real-world problems for developers.

> This package removes the `final` keyword in specific vendor packages so classes that were previously marked final can be extended.

This does not provide a concrete use case.  It is a philosophical position at best.

So, beyond the philosophical "developers should not be impeded by the use of the final or private keywords in the programming language" position that you seem to think is the One Right Way™ to open-source code, what is the practical use of a package like this?  What are the real-world use cases for a package where creating a fork of the upstream source code to bypass the design decisions of the upstream vendor solves?

**Comment by stevebauman** [comment]
@mbabker 

> This issue should be re-opened, or converted to a discussion using the appropriate GitHub feature (presuming it was enabled on this repository).

No. I have answered the question.

> You have managed to skirt around answering both questions posed by the OP with a purely philosophical answer.

No. That is objectively false. The answer I provided is exactly what the purpose of the package is. It is absolutely not "philosophical" by any means. The `final` keyword disables inheritance. This package removes the `final` keyword in vendor packages you define, so that you may extend classes that were previously marked `final`. That is *literally* and *objectively* its purpose.

> So, beyond the philosophical "developers should not be impeded by the use of the final or private keywords in the programming language" position that you seem to think is the One Right Way™ to open-source code

You're making complete of assumptions of my thoughts, and also putting words in my mouth. I have never said or claimed any such thing.

> , what is the practical use of a package like this? What are the real-world use cases for a package where creating a fork of the upstream source code to bypass the design decisions of the upstream vendor solves?

You've made your position clear on this, and I do not owe you any further explanation. If you do not have a use for this package, move along.

**Comment by mbabker** [comment]
> > So, beyond the philosophical "developers should not be impeded by the use of the final or private keywords in the programming language" position that you seem to think is the One Right Way™ to open-source code
> 
> You're making complete of assumptions of my thoughts, and also putting words in my mouth. I have never said or claimed any such thing.

I'd say https://twitter.com/ste_bau/status/1393287684681043970 makes a pretty clear statement, but OK then.

> > , what is the practical use of a package like this? What are the real-world use cases for a package where creating a fork of the upstream source code to bypass the design decisions of the upstream vendor solves?
> 
> You've made your position clear on this, and I do not owe you any further explanation. If you do not have a use for this package, move along.

Actually, I have a legitimate use case for bypassing the final keyword, and have been using `dg/bypass-finals` for that purpose for a few years now.  You can take a look at the tests for https://github.com/Pagerfanta/doctrine-mongodb-odm-adapter/tree/4.x for that use case.  As much as I'd rather not need tooling like unfinalize or `dg/bypass-finals`, I also recognize that there are cases for it to exist (and in all honesty, because I'm not interested in testing the entire database interaction there but only that the adapter code is bridging through correctly, I'd rather get rid of the final keyword in this specific case than deal with a "pure" implementation that requires extra external resources).

Yes, my position is that unfinalize and `dg/bypass-finals` have no place in production code, but I'm also a pragmatist and if they're going to exist and be used, I'd rather see the authors convey clear and concise use cases for these tools instead of just encouraging folks to install them and blindly modify third party code.  To me, the way this package has been promoted comes across as "I want my third party code to follow my development philosophy of 'no final', and this is my way of accomplishing it", and I personally disagree with that as its main reason for existing.

**Comment by stevebauman** [comment]
> I'd say https://twitter.com/ste_bau/status/1393287684681043970 makes a pretty clear statement, but OK then.

My original statement still stands. What you claimed is incorrect, and misconstrued.

> Actually, I have a legitimate use case for bypassing the final keyword

> As much as I'd rather not need tooling like unfinalize or dg/bypass-finals, I also recognize that there are cases for it to exist 

Then what are you going on about?

> To me, the way this package has been promoted comes across as "I want my third party code to follow my development philosophy of 'no final', and this is my way of accomplishing it", and I personally disagree with that as its main reason for existing.

Can't say anything about that. You've came up with your own hypothetical purpose for this package, and then disagree with it.

Let me be clear. I support developers doing whatever they please with open source MIT code. Whatever their philosophy is, I really don't care.

**Comment by mbabker** [comment]
> > To me, the way this package has been promoted comes across as "I want my third party code to follow my development philosophy of 'no final', and this is my way of accomplishing it", and I personally disagree with that as its main reason for existing.
> 
> Can't say anything about that. You've came up with your own hypothetical purpose for this package, and then disagree with it.

Well then let me ask the pointed question, then.  Why is it so difficult to demonstrate practical use cases for a package like this beyond this marketing blurb:

> Unleash the freedom lost with open source PHP packages marking classes and methods as final.

This is, to me, part of what creates the perception of "this exists only because I want it to".  I've watched enough arguments against final and private happen enough times to know that people have strong feelings about it, but I can't say I've ever personally seen anyone make a case for why those two keywords are so bad beyond the philosophical aspect of it.  To me, if it's really such a big issue that you've needed to write and release this tool, I would hope that there's some practical use case, even if it falls into the niche "I can't be bothered to set up a database to test a bridging layer" testing scenario I used.  At least `dg/bypass-finals` tries to present a [primary use case](https://github.com/dg/bypass-finals#introduction), and it lives in the same space as this package as far as what problem it aims to solve.  And yes, I do realize that `composer-patches` is a thing; it's pretty much impossible to run a Drupal site without it.

> Let me be clear. I support developers doing whatever they please with open source MIT code. Whatever their philosophy is, I really don't care.

Believe it or not, I actually have no issue with this package existing, or with folks using it.  Actually, I'm more bothered by the folks who are now shipping updates to their packages to force Composer to conflict their packages with this tool.  I just dislike the way this package has been presented (or the way some folks have spoken of this package or the people who don't 100% support this), and I don't think encouraging folks to blindly use it is in anyone's best interests.

**Comment by misterabdul** [comment]
Okay, I see.

I've done some Google searches and I think one reason the `final` keyword exists is this from the Open-Closed Principle:
> Software Entities (Classes, Modules, Functions, etc.) should be open for Extension, but closed for Modification.

If that is the case, then I kind of agree this package should be used for testing purposes only (maybe to test private methods in the final class or something?). If this package is used just to remove the `final` in the production code, I think it just breaks the Open-Closed Principle.

I'd like to hear more opinions about this.

**Comment by ww9** [comment]
With due respect for my fellow devs, code should be used as one pleases.

As far as I know, there is no one true way of doing things in programming. That would be dogmatic. And principles like the Open-Closed don't exist in a vacuum. Context must be taken into consideration.

This package is not forced upon anyone. It is not for us to tell the author what is right or wrong.

They shared their work for free. And I'm grateful. Sometimes I just need to extend some small functionality and this is much more practical than forking and maintaining an entire repo.

**Comment by cAstraea** [comment]
mbaker ok here's one. I need a way to send emails to this address in laravel 9+ 
abc-defg...06.23@docomo.co.jp
/vendor/symfony/mime is vehemently rejecting it in 
   if (!self::$validator->isValid($this->address, class_exists(MessageIDValidation::class) ? new MessageIDValidation() : new RFCValidation())) {
            throw new RfcComplianceException(sprintf('Email "%s" does not comply with addr-spec of RFC 2822.', $address));
        } despite it being a real email address and Docomo messing up by not following the RFC there is no way of getting around this. Another option would be to some      "exclude-from-classmap": [] sorcery and replace that file with my own version.
